# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import glossary_pb2 as glossary__pb2


class GlossaryServiceStub(object):
    """============ Services ============

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllItems = channel.unary_unary(
                '/glossary.GlossaryService/GetAllItems',
                request_serializer=glossary__pb2.GetAllGlossaryItemsRequest.SerializeToString,
                response_deserializer=glossary__pb2.GetAllGlossaryItemsResponse.FromString,
                )
        self.CreateItem = channel.unary_unary(
                '/glossary.GlossaryService/CreateItem',
                request_serializer=glossary__pb2.CreateGlossaryItemRequest.SerializeToString,
                response_deserializer=glossary__pb2.GlossaryItemResponse.FromString,
                )
        self.UpdateItem = channel.unary_unary(
                '/glossary.GlossaryService/UpdateItem',
                request_serializer=glossary__pb2.UpdateGlossaryItemRequest.SerializeToString,
                response_deserializer=glossary__pb2.GlossaryItemResponse.FromString,
                )
        self.DeleteItem = channel.unary_unary(
                '/glossary.GlossaryService/DeleteItem',
                request_serializer=glossary__pb2.DeleteGlossaryItemRequest.SerializeToString,
                response_deserializer=glossary__pb2.GlossaryItemResponse.FromString,
                )


class GlossaryServiceServicer(object):
    """============ Services ============

    """

    def GetAllItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlossaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllItems,
                    request_deserializer=glossary__pb2.GetAllGlossaryItemsRequest.FromString,
                    response_serializer=glossary__pb2.GetAllGlossaryItemsResponse.SerializeToString,
            ),
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=glossary__pb2.CreateGlossaryItemRequest.FromString,
                    response_serializer=glossary__pb2.GlossaryItemResponse.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=glossary__pb2.UpdateGlossaryItemRequest.FromString,
                    response_serializer=glossary__pb2.GlossaryItemResponse.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=glossary__pb2.DeleteGlossaryItemRequest.FromString,
                    response_serializer=glossary__pb2.GlossaryItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'glossary.GlossaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GlossaryService(object):
    """============ Services ============

    """

    @staticmethod
    def GetAllItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/glossary.GlossaryService/GetAllItems',
            glossary__pb2.GetAllGlossaryItemsRequest.SerializeToString,
            glossary__pb2.GetAllGlossaryItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/glossary.GlossaryService/CreateItem',
            glossary__pb2.CreateGlossaryItemRequest.SerializeToString,
            glossary__pb2.GlossaryItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/glossary.GlossaryService/UpdateItem',
            glossary__pb2.UpdateGlossaryItemRequest.SerializeToString,
            glossary__pb2.GlossaryItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/glossary.GlossaryService/DeleteItem',
            glossary__pb2.DeleteGlossaryItemRequest.SerializeToString,
            glossary__pb2.GlossaryItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class LinkServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllLinks = channel.unary_unary(
                '/glossary.LinkService/GetAllLinks',
                request_serializer=glossary__pb2.GetAllLinksRequest.SerializeToString,
                response_deserializer=glossary__pb2.GetAllLinksResponse.FromString,
                )
        self.CreateLink = channel.unary_unary(
                '/glossary.LinkService/CreateLink',
                request_serializer=glossary__pb2.CreateLinkRequest.SerializeToString,
                response_deserializer=glossary__pb2.LinkResponse.FromString,
                )
        self.UpdateLink = channel.unary_unary(
                '/glossary.LinkService/UpdateLink',
                request_serializer=glossary__pb2.UpdateLinkRequest.SerializeToString,
                response_deserializer=glossary__pb2.LinkResponse.FromString,
                )
        self.DeleteLink = channel.unary_unary(
                '/glossary.LinkService/DeleteLink',
                request_serializer=glossary__pb2.DeleteLinkRequest.SerializeToString,
                response_deserializer=glossary__pb2.LinkResponse.FromString,
                )


class LinkServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllLinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LinkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllLinks,
                    request_deserializer=glossary__pb2.GetAllLinksRequest.FromString,
                    response_serializer=glossary__pb2.GetAllLinksResponse.SerializeToString,
            ),
            'CreateLink': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLink,
                    request_deserializer=glossary__pb2.CreateLinkRequest.FromString,
                    response_serializer=glossary__pb2.LinkResponse.SerializeToString,
            ),
            'UpdateLink': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLink,
                    request_deserializer=glossary__pb2.UpdateLinkRequest.FromString,
                    response_serializer=glossary__pb2.LinkResponse.SerializeToString,
            ),
            'DeleteLink': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteLink,
                    request_deserializer=glossary__pb2.DeleteLinkRequest.FromString,
                    response_serializer=glossary__pb2.LinkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'glossary.LinkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LinkService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/glossary.LinkService/GetAllLinks',
            glossary__pb2.GetAllLinksRequest.SerializeToString,
            glossary__pb2.GetAllLinksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/glossary.LinkService/CreateLink',
            glossary__pb2.CreateLinkRequest.SerializeToString,
            glossary__pb2.LinkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/glossary.LinkService/UpdateLink',
            glossary__pb2.UpdateLinkRequest.SerializeToString,
            glossary__pb2.LinkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/glossary.LinkService/DeleteLink',
            glossary__pb2.DeleteLinkRequest.SerializeToString,
            glossary__pb2.LinkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
